/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";var a=Object.defineProperty;var r=Object.getOwnPropertyDescriptor;var l=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var m=(e,o)=>{for(var s in o)a(e,s,{get:o[s],enumerable:!0})},f=(e,o,s,n)=>{if(o&&typeof o=="object"||typeof o=="function")for(let t of l(o))!c.call(e,t)&&t!==s&&a(e,t,{get:()=>o[t],enumerable:!(n=r(o,t))||n.enumerable});return e};var h=e=>f(a({},"__esModule",{value:!0}),e);var k={};m(k,{default:()=>d});module.exports=h(k);var i=require("obsidian"),d=class extends i.Plugin{async onload(){this.addCommand({id:"show-cursor-line",name:"\u663E\u793A\u5F53\u524D\u884C\u53F7",hotkeys:[{modifiers:["Mod","Shift"],key:"L"}],editorCallback:o=>{let s=o.getCursor().line+1;new i.Notice(`\u{1F4CD} \u5F53\u524D\u884C\u53F7\uFF1A${s}`)}})}};
